name: Build Frontend and Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build and Copy Dev
        run: |
          npm install --global yarn
          cd zt_frontend
          yarn install
          yarn run build
          cd ..
          rm -rf zt_backend/dist_dev
          mkdir -p zt_backend/dist_dev
          cp -r zt_frontend/dist/* zt_backend/dist_dev

      - name: Build and Copy App
        run: |
          cd zt_frontend
          yarn install
          yarn run buildapp
          cd ..
          rm -rf zt_backend/dist_app
          mkdir -p zt_backend/dist_app
          cp -r zt_frontend/dist/* zt_backend/dist_app
      
      - name: Build Docs
        run: |
          python -m pip install --upgrade pip
          pip install autodoc_pydantic
          pip install furo
          sphinx-build -b html docs docs/html

      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.ZT_PAT }}
          branch: main
          unprotect_reviews: true
